"""empty message

Revision ID: 622cc6c11f2d
Revises: 
Create Date: 2026-02-15 10:07:47.764305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '622cc6c11f2d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('razorpay_order_id', sa.String(length=100), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=100), nullable=True),
    sa.Column('credits_purchased', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razorpay_order_id')
    )
    with op.batch_alter_table('job_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_seeded', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('external_link', sa.String(length=255), nullable=True))
        batch_op.alter_column('recruiter_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tier', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('credits', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('subscription_active_until', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('razorpay_customer_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('razorpay_customer_id')
        batch_op.drop_column('subscription_active_until')
        batch_op.drop_column('credits')
        batch_op.drop_column('tier')

    with op.batch_alter_table('job_posts', schema=None) as batch_op:
        batch_op.alter_column('recruiter_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('external_link')
        batch_op.drop_column('is_seeded')

    op.drop_table('transactions')
    # ### end Alembic commands ###
